---
exclude_paths:
  - '.git/**'
  - '.github/**'
  - '*.md'
  - '*.ps1'
  - '.idea/**'
  - '.*/**/jdi-light-html/**'
  - '.jdi-light-html/**'
  - '.*/**/jdi-light-html-tests/**'
  - '.jdi-light-html-tests/**'
