language: java
before_install:
  - sudo apt-get -y install jq
  - java -Xmx32m -version
before_script:
  - ls -lah
  - google-chrome-stable --version
addons:
  chrome: stable
  apt:
    packages:
      - openjdk-8-jdk

env:
  global:
    - CHROME_PROPERTIES="chrome.properties"
    - WITH_PARAMS="-Ddriver=chrome -Dchrome.capabilities.path=$CHROME_PROPERTIES" #add -ntp when maven will be >=3.6.1 on travis
    - UNIT="-Punit"
    - COMMON="-Pcommon"
    - COMPLEX="-Pcomplex"
    - GROUP_ID="com.epam.jdi"
    - NOPO_TESTS="jdi-bdd-no-po-tests"
    - NOPO_TESTS_PROPERTY="test-examples/jdi-bdd-no-po-tests"
    - BDD_TESTS="jdi-bdd-tests"
    - BOOTSTRAP_TESTS="jdi-light-bootstrap-tests"
    - HTML_TESTS="jdi-light-html-tests"
    - ANGULAR_TESTS="jdi-light-angular-tests"
    - ANGULAR_TESTS_WITH_MOCKS="jdi-light-angular-tests-with-mocks"
    - EXAMPLES="jdi-light-examples"
    - EXAMPLES_PROPERTY="test-examples/jdi-light-examples"
    - PERFORMANCE="jdi-performance"
    - PERFORMANCE_PROPERTY="test-examples/jdi-performance"
    - CHROME_ARGS="--headless --window-size=1920,1080"
    - PATH="$JAVA_HOME/bin:$PATH"

stages:
  - prepare
  - compile
  - test
  - reports

cron_condition: &cron_condition
  if: (branch = master) AND (type IN (cron, api))
  #Stages that refer to cron_condition would trigger only under specified conditions
testshtml: &testshtml
  stage: test
  name: Run tests - html
  <<: *cron_condition
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$HTML_TESTS/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$HTML_TESTS

jobs:
  include:
    - stage: prepare
      name: Welcome to jdi
      script:
        - echo ------------------- WELCOME TO JDI ----------------------
        - mvn --version #it is helpful

    - stage: compile
      name: Compile jdi code
      script:
        - mvn install -DskipTests

    - <<: *testshtml
      name: Run tests - html - JDK8
      if: true
      jdk: openjdk8
    - <<: *testshtml
      name: Run tests - html - JDK9
      jdk: openjdk9
    - <<: *testshtml
      name: Run tests - html - JDK10
      if: true
      jdk: openjdk10
    - <<: *testshtml
      name: Run tests - html - JDK11
      jdk: openjdk11
    - <<: *testshtml
      name: Run tests - html - JDK12
      jdk: openjdk12
    - <<: *testshtml
      name: Run tests - html - JDK13
      jdk: openjdk13


    - stage: reports
      name: Deploy allure reports to netlify
      script:
        - npm install -g allure-commandline
        - npm install -g netlify-cli
        - allure --version
        - source reports.sh
        - deployAllureResults
after_failure:
  - echo "Build was failed"
after_success:
  - echo "Build was successful"

notifications:
  webhooks:
    urls:
      - https://outlook.office.com/webhook/ac8f242a-5a99-4fab-a4d7-799de8968df5@b41b72d0-4e9f-4c26-8a69-f949f367c91d/TravisCI/116217b941a943a3a545d6290e152c78/1d65db1e-26ce-4372-9a58-9c3635f1f0bd
    if: type = cron
    on_success: always
    on_failure: always

after_script:
  # following 4 lines are to rename allure-results dir to allure-results-<JDK VERSION>
  - ALLURE_RESULTS=$(find -type d -regex ".*/jdi.*/target/allure-results")
  - ALLURE_RESULTS_JDK=$ALLURE_RESULTS-$TRAVIS_JDK_VERSION
  - mv $ALLURE_RESULTS $ALLURE_RESULTS_JDK
  - echo "$ALLURE_RESULTS dir has been renamed to $ALLURE_RESULTS_JDK"
  - echo "JDK_VERSION=$TRAVIS_JDK_VERSION" > "$ALLURE_RESULTS_JDK/environment.properties"
  - echo "BRANCH=$TRAVIS_BRANCH" >> "$ALLURE_RESULTS_JDK/environment.properties"
  # further actions
  - source reports.sh
  - grubAllureResults
  - du -d 1 -h ./
  - ls -la
# extra time during long builds
install:
  - travis_wait
